#!/bin/bash

# 编译代码
docker run --rm \
  -v $PWD:/go/src/GP \
  -w /go/src/GP \
  -p 80:80 \
  golang:1.12.14 go build

IMAGE="ccr.ccs.tencentyun.com/go_gp/go_gp:latest"

# 编译镜像
docker build -t $IMAGE .

docker run -p 8000:8000 --name go-test $IMAGE

#docker tag 705105278/go_gp $IMAGES

# 上传镜像 (请提前登录好,docker login 只需登录一次)
docker push $IMAGE

# 清理
docker rmi $IMAGE

rm GP