#! /bin/bash

# 编译代码
docker run --rm \
  -v $PWD:/go/src/GP \
  -w /go/src/GP \
  golang:alpine go build



IMAGE="ccr.ccs.tencentyun.com/go_gp/go_gp:latest"
docker login --username=100004230223 ccr.ccs.tencentyun.com
echo $IMAGE
# 编译镜像
docker build -t $IMAGE .

#docker tag latest $IMAGE
# 上传镜像 (请提前登录好,docker login 只需登录一次)
docker push $IMAGE

# 清理
docker rmi $IMAGE
rm go_gp