package constant

const (
	SUCCESS                      = 200
	ACCOUNT_HAS_BEEN_REGISTER    = 300
	ACCOUNT_HAS_BEEN_EXIST       = 301
	PASSWORD_NOT_RIGHT           = 302
	ACCOUNT_HAS_BEEN_BAN         = 303
	STATUS_INTERNAL_SERVER_ERROR = 500
	PARMAS_EMPTY                 = 501
	NEWFRIEND_HAS_BEEN_EXIST     = 600
	PASSFRIEND_NOT_EXIST         = 601
	TOKEN_IS_EXPIRED             = 1001
)
